str1 = "The quick brown cat jumps over the lazy dog."
print("Original vector(string)")
print(str1)
print("Unique elements of the given string:")
print(unique(tolower(str1)))
nums = c(1, 2, 2, 3, 4, 4, 5, 6)
print("Original vector(number)")
print(nums)
print("Unique elements of vector:")
print(unique(nums))
