print("first 10 letters in lower case:")
t = head(letters,10)
print(t)
print("last 10 letters in upper case:")
t = tail(letters,10)
print(t)
print("letters between 22nd to 24th letters in upper case:")
e = tail(letters[22:24])
print(e)
